#!/usr/bin/env python3
"""Refresh _data/downloads.yml: file sizes and last-updated dates for the
download page.

Scans election-data.md for every link into the data repository, then for each
file path asks
  - the media mirror (media.githubusercontent.com) for Content-Length, which is
    the size the browser actually downloads (the GitHub contents API reports
    the size of the Git LFS pointer instead), and
  - the GitHub commits API (via `gh api`, so it uses your existing login) for
    the date of the last commit that touched the CSV (RDS if there is no CSV).

Output: _data/downloads.yml keyed by file stem, e.g.

  municipal_unharm:
    csv_mb: 12.3
    rds_mb: 4.1
    xlsx_mb: 9.8
    updated: 2026-08-19

Run after the data repository publishes new files:

  python3 scripts/update_download_data.py
"""
import concurrent.futures
import json
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

REPO = "awiedem/german_election_data"
MIRROR = f"https://media.githubusercontent.com/media/{REPO}/refs/heads/main/"
ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "election-data.md"
OUT = ROOT / "_data" / "downloads.yml"
LINK = re.compile(r"https://github\.com/" + re.escape(REPO) + r"/raw/refs/heads/main/(data/[^)\s?\"]+)")


def content_length(path):
    req = urllib.request.Request(MIRROR + path, method="HEAD", headers={"User-Agent": "gerda-site"})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            n = resp.headers.get("Content-Length")
            return int(n) if n else None
    except Exception as exc:  # noqa: BLE001
        print(f"  size failed for {path}: {exc}", file=sys.stderr)
        return None


def last_commit_date(path):
    cmd = ["gh", "api", f"repos/{REPO}/commits?path={path}&per_page=1",
           "--jq", ".[0].commit.committer.date"]
    try:
        out = subprocess.run(cmd, check=True, capture_output=True, text=True, timeout=60).stdout.strip()
        return out[:10] if out else None
    except Exception as exc:  # noqa: BLE001
        print(f"  date failed for {path}: {exc}", file=sys.stderr)
        return None


def main():
    text = PAGE.read_text(encoding="utf-8")
    paths = sorted(set(LINK.findall(text)))
    if not paths:
        sys.exit("no data links found in election-data.md")
    print(f"{len(paths)} files linked from election-data.md")

    with concurrent.futures.ThreadPoolExecutor(8) as ex:
        sizes = dict(zip(paths, ex.map(content_length, paths)))
    with concurrent.futures.ThreadPoolExecutor(4) as ex:
        dates = dict(zip(paths, ex.map(last_commit_date, paths)))

    data = {}
    for path in paths:
        stem, ext = Path(path).stem, Path(path).suffix.lstrip(".")
        entry = data.setdefault(stem, {})
        if sizes[path] is not None:
            entry[f"{ext}_mb"] = round(sizes[path] / 1e6, 1)
        # The date comes from the CSV (RDS as fallback): CSV and RDS are
        # regenerated together when data change, whereas the Excel exports
        # were added in one sweep and would date every dataset to that day.
        if dates[path] and (ext == "csv" or (ext == "rds" and "updated" not in entry)):
            entry["updated"] = dates[path]

    OUT.parent.mkdir(exist_ok=True)
    lines = ["# Generated by scripts/update_download_data.py; do not edit by hand.", ""]
    for stem in sorted(data):
        lines.append(f"{stem}:")
        for key in sorted(data[stem]):
            lines.append(f"  {key}: {data[stem][key]}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    missing = [p for p in paths if sizes[p] is None or not dates[p]]
    print(f"wrote {OUT.relative_to(ROOT)} with {len(data)} datasets; {len(missing)} lookups failed")
    for p in missing:
        print("  ", p)


if __name__ == "__main__":
    main()
